/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaMetodosIterativos.java
 *
 * Created on May 30, 2011, 6:40:18 PM
 */

package Interfaz;

import Funciones.MetodosSistemaDeEcuaciones;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author santiago
 */
public class PantallaMetodosIterativos extends javax.swing.JFrame {

    private DefaultTableModel modeloMatriz;
    private DefaultTableModel modeloVector;
    private int iter = 0;
    private double lambda = 0;
    private double tol = 0;
    public PantallaMetodosIterativos() {
        initComponents();
        bMatriz.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatriz = new javax.swing.JTable();
        rJacobi = new javax.swing.JRadioButton();
        rGaussSeidel = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tNum = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVector = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tTolerancia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tLambda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tIteraciones = new javax.swing.JTextField();
        bEjecutar = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        bMatriz = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpResultados = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/sinergia88x99.png"))); // NOI18N

        tblMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMatriz);

        buttonGroup1.add(rJacobi);
        rJacobi.setText("Jacobi");
        rJacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rJacobiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rGaussSeidel);
        rGaussSeidel.setText("Gauss-Seidel");
        rGaussSeidel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rGaussSeidelActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de variables");

        tblVector.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblVector);

        jLabel3.setText("Tolerancia ");

        jLabel4.setText("Lambda");

        jLabel5.setText("Iteraciones");

        bEjecutar.setText("Ejecutar");
        bEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEjecutarActionPerformed(evt);
            }
        });

        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        bMatriz.setText("Crear Matriz");
        bMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMatrizActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(tpResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tNum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(bMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rJacobi)
                                        .addGap(137, 137, 137)
                                        .addComponent(rGaussSeidel))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tLambda, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                            .addComponent(tTolerancia, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                            .addComponent(tIteraciones, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(631, Short.MAX_VALUE)
                .addComponent(bEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rJacobi)
                    .addComponent(rGaussSeidel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMatriz))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tTolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tLambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tIteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(bEjecutar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(bAtras))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public double[][] readA(int a){
        double matriz[][] = new double [a + 1][a + 1];
        for(int i = 0; i < a; i++){
            for(int j = 0; j < a; j++){

                matriz[i][j] = Double.valueOf(tblMatriz.getValueAt(i, j).toString());
            }
        }
        return matriz;
    }
    public double[] readB(int a){
        double b[] = new double[a];
        for(int i =  0 ; i < a; i++ ){
            b[i] = Double.valueOf(tblMatriz.getValueAt(i, a).toString());
        }
        return b;
    }

    public double[] readVector(int a){
        double vector[] = new double[a];
        for(int i = 0; i < a; i++){
            vector[i] = Double.valueOf(tblMatriz.getValueAt(1, i).toString());
        }
        return vector;
    }
    private void bMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMatrizActionPerformed
        modeloMatriz = new DefaultTableModel();
        modeloVector = new DefaultTableModel();
        tpResultados.setText("");
        int num = Integer.parseInt(tNum.getText());
        String[] titulos = new String[num + 1];
        Double[][] matriz = new Double[num][num + 1];
        Double [][] vector = new Double[1][num];
        String [] titulos2 = new String[num];
        int cont = 0;
        while(cont <= num){
            titulos[cont] = "X" + (cont+1);
            cont++;
        }
        titulos[num] = "b";
        modeloMatriz.setDataVector(matriz, titulos);
        modeloVector.setDataVector(vector,titulos2);

       tblMatriz.setModel(modeloMatriz);
       tblVector.setModel(modeloVector);


    }//GEN-LAST:event_bMatrizActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_bAtrasActionPerformed

    private void bEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEjecutarActionPerformed
        try{
        tpResultados.setText("");
        iter = Integer.parseInt(tIteraciones.getText());
        tol =  Double.valueOf(tTolerancia.getText());
        lambda = Double.valueOf(tLambda.getText());
        int num = Integer.parseInt(tNum.getText());
        double [] vector = new double[num];
        
        if(rJacobi.isSelected()){
            MetodosSistemaDeEcuaciones.jacobi(readA(num), readB(num), readVector(num), num, iter, tol, lambda);
            tpResultados.setText(MetodosSistemaDeEcuaciones.res);
        }
        if(rGaussSeidel.isSelected()){
            MetodosSistemaDeEcuaciones.gaussSeidel(readA(num), readB(num), readVector(num), num, iter, tol, lambda);
            tpResultados.setText(MetodosSistemaDeEcuaciones.res);
        }

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese Correctamente los datos");
        }
    }//GEN-LAST:event_bEjecutarActionPerformed

    private void rJacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rJacobiActionPerformed
        bMatriz.setEnabled(true);
    }//GEN-LAST:event_rJacobiActionPerformed

    private void rGaussSeidelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rGaussSeidelActionPerformed
        bMatriz.setEnabled(true);
    }//GEN-LAST:event_rGaussSeidelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaMetodosIterativos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bEjecutar;
    private javax.swing.JButton bMatriz;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rGaussSeidel;
    private javax.swing.JRadioButton rJacobi;
    private javax.swing.JTextField tIteraciones;
    private javax.swing.JTextField tLambda;
    private javax.swing.JTextField tNum;
    private javax.swing.JTextField tTolerancia;
    private javax.swing.JTable tblMatriz;
    private javax.swing.JTable tblVector;
    private javax.swing.JTextPane tpResultados;
    // End of variables declaration//GEN-END:variables

}
