/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaInterpolacion.java
 *
 * Created on May 31, 2011, 12:02:33 AM
 */

package Interfaz;

import Funciones.MetodosInterpolacion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Arrays;

/**
 *
 * @author santiago
 */
public class PantallaInterpolacion extends javax.swing.JFrame {

    private DefaultTableModel modeloMatriz;
    public PantallaInterpolacion() {
        initComponents();
        bAceptar.setEnabled(false);
        bInterpolar.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tNum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpResultados = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        rNewton = new javax.swing.JRadioButton();
        rLagrage = new javax.swing.JRadioButton();
        bMetodos = new javax.swing.JButton();
        rSpline = new javax.swing.JRadioButton();
        bEjecutar = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();
        bInterpolar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/sinergia88x99.png"))); // NOI18N

        jLabel2.setText("Numero de puntos");

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTable);

        jScrollPane2.setViewportView(tpResultados);

        buttonGroup1.add(rNewton);
        rNewton.setText("Newton");
        rNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNewtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(rLagrage);
        rLagrage.setText("Lagrange");
        rLagrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLagrageActionPerformed(evt);
            }
        });

        bMetodos.setText("Otros Metodos");
        bMetodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMetodosActionPerformed(evt);
            }
        });

        buttonGroup1.add(rSpline);
        rSpline.setText("Splines lineal");
        rSpline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSplineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rNewton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(rLagrage)
                        .addGap(80, 80, 80)
                        .addComponent(bMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rSpline)
                        .addContainerGap(551, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rNewton)
                    .addComponent(bMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rLagrage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSpline)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        bEjecutar.setText("Ejecutar");
        bEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEjecutarActionPerformed(evt);
            }
        });

        bAtras.setText("Atras");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bInterpolar.setText("Interpolar con esta funcion");
        bInterpolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInterpolarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNum, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(bAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(bInterpolar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(bEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addComponent(bAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bInterpolar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAtras)
                    .addComponent(bEjecutar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        modeloMatriz = new DefaultTableModel();
        tpResultados.setText("");
        int num = Integer.parseInt(tNum.getText());
        String[] titulos = new String[num + 1];
        Double [][] matriz = new Double[2][num + 1];
        int cont = 0;
        while(cont <= num){
            titulos[cont] = cont + "";
            cont++;
        }
        modeloMatriz.setDataVector(matriz, titulos);
        tblTable.setModel(modeloMatriz);
        tblTable.setValueAt("X", 0, 0);
        tblTable.setValueAt("y", 1, 0);
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEjecutarActionPerformed
        tpResultados.setText("");
        bInterpolar.setEnabled(true);
        try{
        if(rNewton.isSelected()){
            MetodosInterpolacion.newton(readx(Integer.parseInt(tNum.getText())), ready(Integer.parseInt(tNum.getText())), Integer.parseInt(tNum.getText()));
            tpResultados.setText("Polinomio : " + MetodosInterpolacion.res);
        }
        if(rLagrage.isSelected()){
            MetodosInterpolacion.lagrange(readx(Integer.parseInt(tNum.getText())), ready(Integer.parseInt(tNum.getText())), Integer.parseInt(tNum.getText()));
            tpResultados.setText("Polinomio : " + MetodosInterpolacion.res);
        }
        if(rSpline.isSelected()){
            bInterpolar.setEnabled(false);
            MetodosInterpolacion.splinesLineal(readx(Integer.parseInt(tNum.getText())), ready(Integer.parseInt(tNum.getText())), Integer.parseInt(tNum.getText()));
            tpResultados.setText(MetodosInterpolacion.res);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Por favor ingrese correctamente los valores requeridos");
        }
    }//GEN-LAST:event_bEjecutarActionPerformed

    private void rNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNewtonActionPerformed
        bAceptar.setEnabled(true);
        bInterpolar.setEnabled(false);
    }//GEN-LAST:event_rNewtonActionPerformed

    private void rLagrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLagrageActionPerformed
        bAceptar.setEnabled(true);
        bInterpolar.setEnabled(false);
    }//GEN-LAST:event_rLagrageActionPerformed

    private void rSplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSplineActionPerformed
        bAceptar.setEnabled(true);
        bInterpolar.setEnabled(false);
    }//GEN-LAST:event_rSplineActionPerformed

    private void bInterpolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInterpolarActionPerformed
        PantallaInterpolante pint = new PantallaInterpolante();
        pint.setVisible(true);
    }//GEN-LAST:event_bInterpolarActionPerformed

    private void bMetodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMetodosActionPerformed

        PantallaOtrosMetodosInterpolacion pomi = new PantallaOtrosMetodosInterpolacion();
        pomi.setVisible(true);
    }//GEN-LAST:event_bMetodosActionPerformed

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        this.dispose();
        PantallaMetodos pm = new PantallaMetodos();
        pm.setVisible(true);
    }//GEN-LAST:event_bAtrasActionPerformed
    public double[] readx(int a){
        double[] x = new double[a];
        for(int i = 1; i < a; i++){
            x[i-1] = Double.valueOf(tblTable.getValueAt(0, i).toString());
        }
        return x;
    }
     public double[] ready(int a){
        double[] y = new double[a];
        for(int i = 1; i < a; i++){
            y[i -1] = Double.valueOf(tblTable.getValueAt(1, i).toString());
        }
        return y;
    }
    public void print(double a[]){
        for(int i = 0; i < a.length; i++){
            System.out.print(a[i] + "  ");
        }
        System.out.println();
    }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInterpolacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bEjecutar;
    private javax.swing.JButton bInterpolar;
    private javax.swing.JButton bMetodos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rLagrage;
    private javax.swing.JRadioButton rNewton;
    private javax.swing.JRadioButton rSpline;
    private javax.swing.JTextField tNum;
    private javax.swing.JTable tblTable;
    private javax.swing.JTextPane tpResultados;
    // End of variables declaration//GEN-END:variables

}
